api/common/axios.ts
api/common/path.ts
api/formPage/getItemData.ts
api/giver/payReady.ts
components/common/presentImageBox.tsx
components/formPage/itemLink.tsx
constant/queryKey.ts
next.config.js
package.json
pages/formPage.tsx
types/queryKeyType.ts
validation/input.ts

- close #15 
- axios를 외부 서버에 접근하려니깐 cors에러가 나서 구글링한 내용으로 임시방편으로 구현했어요! 아마 이후에 서버에게 부탁해서 이 부부분은 다시 구현해야할거 같아요!
- 링크를 통해 정보를 가져오는 부분은 코드도 길어질거 같아서 컴포넌트를 따로 분리하여서 진행했습니다!

Feat#15 form page/item crawling

---

components/modal/BankModal.tsx
pages/formPage.tsx
types/wishesData.ts
validation/input.ts

- close #16 
- 각 입력을 useInput or useState를 통해서 선언,할당해줬어요.
- 아직 모달에 관련된 훅은 구현하지 못했습니다... 
- 입력에 들어가는 값들을 객체로 선언하지않고 각각의 상태로 저장했는데 이에 대해서 어떻게 생각하는지 궁금해요!

Feat#16 form page/state

---

api/formPage/getItemData.ts
api/formPreviewPage/createWishesLink.ts
api/kakaoLogin/login.ts
components/cakes/approve/successItemBox.tsx
components/modal/ShareModal.tsx
pages/cakes/approve/index.tsx
pages/wishes/preview/index.tsx
pages/wishes/share/index.tsx
recoil/auth/loginUserInfo.ts
types/auth/loginUserInfo.ts

Kakao login/test

---

containers/main/index.tsx
hooks/useAuthKakao.ts
pages/main.tsx

- close #47 
- 메인페이지 리팩토링
- 컨벤션에 맞게 수정
- 전체 로직을 container로 분리해서 페이지 안에 하나의 컴포넌트만 들어가게 수정
- containers 폴더에 페이지 컴포넌트 넣었습니다

Refactor#47 main

---

pages/_app.tsx
pages/_document.tsx

[ fix ] 카카오 에러 수정

---

api/cakes/cakesAPI.ts
components/cakes/approve/successItemBox.tsx
hooks/queries/login/useAuthKakao.ts
hooks/queries/mypage/useEditWishesInfo.tsx
hooks/queries/wishes/useCreateWishesLink.ts
pages/_app.tsx

Release1.0.0

---

api/wishes/getPresignedURL.ts
hooks/wishes/useUploadItemInfo.ts

[ fix ] 빌드 에러 수정

---

api/login/sendCodeToServer.ts

[ test ] 기존 코드로 변경

---

components/main/index.tsx
components/mypage/index.tsx

- close #
> 소원 수정이 비활성화된 버튼을 누르면 아예 새로운 소원 수정 페이지로 이동
오류 수정

[fix] 마이페이지 버튼 비활성화 오류 수정

---

hooks/useKakaoShare.ts

[test] 카카오 공유하기 테스트

---

components/common/footer.tsx
components/common/layout.tsx
components/login/index.tsx
components/main/index.tsx
components/wishes/[id].tsx
constant/alertMessage.ts
pages/cakes/[id].tsx
pages/cakes/approve/index.tsx
pages/index.tsx
pages/login/oauth2/code/kakao/index.tsx
pages/main/index.tsx
pages/wishes/[id].tsx
styles/GlobalStyle.tsx

[ style ] 전역스타일링 변경 및 레이아웃으로 구조 변경

---

components/common/footer.tsx
components/login/index.tsx
pages/index.tsx

[ fix ] 푸터 위치, 버튼 위치 수정

---

api/wishes/wishesAPI.ts
components/common/layout.tsx
components/common/modal/BankModal.tsx
components/login/index.tsx
components/main/index.tsx
components/wishes/wishesForm/WisehsStep2.tsx
components/wishes/wishesForm/WishesStep1.tsx
components/wishes/wishesForm/itemLink.tsx
next.config.js
utils/common/extractItem.ts

- close #119 
- 전역스타일링 변경
- 네이버 스마트스토어 이미지 파싱 기능구현

Release#119 wishes/qa

---

components/wishes/[id].tsx
components/wishes/share/index.tsx
hooks/queries/login/useAuthKakao.ts

- close #127 
- 펀딩기간이 아닐 시
1. 공유하기 페이지에서 공유 모달창 뜨지않게 수정
2. 선물자의 소원링크(Ex. https://www.sunmulzu.store/wishes/60) 접근 시 예외처리

Release#127 wishes/share

---

api/cakes/cakesAPI.ts
api/common/axios.ts
api/wishes/wishesAPI.ts
components/cakes/index.tsx
components/common/input/inputBox.tsx
components/common/input/inputContainer.tsx
components/common/layout.tsx
components/common/modal/CustomDatePicker.tsx
components/login/index.tsx
components/main/cake.tsx
components/mypage/EditWishes/index.tsx
components/mypage/index.tsx
components/mypage/letters/[id].tsx
components/wishes/[id].tsx
components/wishes/share/index.tsx
components/wishes/wishesForm/BankInfo.tsx
components/wishes/wishesForm/Preview.tsx
components/wishes/wishesForm/WishesStep1.tsx
components/wishes/wishesForm/itemLink.tsx
hooks/queries/cakes/useRequestPayReady.ts
hooks/queries/login/useAuthKakao.ts
hooks/queries/mypage/useEditWishesInfo.tsx
hooks/queries/wishes/useCreateWishesLink.ts
hooks/wishes/useUploadItemInfo.ts
pages/cakes/approve/index.tsx
pages/wishes/[id].tsx
styles/GlobalStyle.tsx
styles/theme.ts
utils/common/extractItem.ts
utils/common/getDate.ts

Release#126 common/style

---

components/common/modal/GuideModal.tsx
components/mypage/index.tsx
components/mypage/itemBox.tsx
components/mypage/links/[id].tsx

Release#129 image,fonts

---

components/common/modal/GuideModal.tsx

[test] 가이드모달 이미지 수정 중

---

components/common/modal/GuideModal.tsx

[fix] 가이드 모달창 수정

---

pages/_app.tsx

[ feat ] GA 커스텀 코드 적용

---

components/mypage/letters/cakeListButton.tsx
components/mypage/letters/lettersMain.tsx

[test] CakeListButton fonts 오류 테스트

---

pages/_document.tsx

[ fix ] GTM 태그 삽입

---

pages/_document.tsx

[ fix ] 환경변수로 변경

---

pages/_app.tsx
pages/_document.tsx

[ chore ] 도메인 정보 수정

---

components/Main/MainCenterContent.tsx

[ fix ] 프로그레스바 수정

---

api/user.ts
components/Common/Modal/BankInput.tsx
components/Wishes/WishesForm/BankInfo.tsx
hooks/queries/user.ts
types/common/box/boxStyleType.ts

- close #175 
정확히 "계좌 인증" 로직만 추가했습니다. 앞뒤로 어떤 컨텍스트가 있는지 잘 파악이 안돼서요.. 그 부분을 중점으로 에러 사항 확인해주심 감사하겠습니다.

Feature/175 user/verify account

---

api/user.ts
components/Common/Modal/BankInput.tsx
components/Wishes/WishesForm/BankInfo.tsx
hooks/queries/user.ts
types/common/box/boxStyleType.ts

main에 merge한 #180 pr을 develop에 합니다

To develop

---

components/Common/Modal/MainShareModal.tsx
constant/queryKey.ts
hooks/queries/wishes.ts

어떤 소원이든 공유할 때 해당 소원의 title이 출력되지 않던 문제 해결

소원 공유 title 핫픽스

---

components/Wishes/WishesForm/WisehsStep2.tsx

[ feat ] 소원 제목 길이 제한 명시

---

components/Layout/EmptyLayout.tsx
components/Layout/HeaderLayout.tsx
components/Layout/index.tsx
components/footer.tsx

- close #196 
- 기존에 구현했던 푸터를 추가했습니다.
- 스타일 수정 반영했습니다.

[ feat ] 푸터 추가 및 스타일 수정

---

components/Cakes/CakesForm.tsx
components/Cakes/CakesPay.tsx
components/Mypage/EditWishes/index.tsx
components/Mypage/index.tsx
components/Wishes/WishesForm/WishesStep1.tsx
components/footer.tsx
pages/_app.tsx

Reverts Make-A-Wish-Sopt/Make-A-Wish-Client#201

Revert "Hotfix/200 footer link"

---

api/wishes.ts
components/Mypage/EditWishes/index.tsx
components/Wishes/WishesForm/UploadPresent.tsx

- close #204
disabled의 조건만 지워주었습니다!

[ fix ] 생일 주간에도 소원수정이 가능하도록 변경

---

components/Wishes/Share/index.tsx

- close #206 
처음 데이터 패칭이 되지 않았던 부분을 useEffect를 통해 초기 렌더링 했을때 데이터를 다시 가져오게 설정했어요

[ fix ] 소원 생성 후 초기 상태 데이터 패칭

---

components/Common/Modal/ModalForm/CloseModal.tsx
components/Login/index.tsx

[ feat ] 종료 알림 팝업 개발
